name : dev Deploy
on: 
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  reusable_workflow:
    uses: DevOpsProjectsOrganization/roboshop-github-actions/.github/workflows/deploy.yml@main
    with : 
      app_name : frontend
      app_env : dev
      enabled : false
      ingress : true